# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 419505f6cbf1ff75ebe16cc78e8853040c66cc77241e0546512c8ce299f4122854a0e2a84d464ad30eef590be1e745369a897ef6bd5a2bf7d3ce0887cd8c3460

test:
  secret_key_base: 7ad136730922912f89f612dfcd90132f231f2c55a38b9339e8ab8eda5c94ebf7d88b4458a41ccb068f38553808db4d2ee5788702bd55aede52c9e85ad028e1c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
